version: '3.7'

services:
  nginx:
    restart: always
    environment:
      TZ: Asia/Tokyo
  letsencrypt:
    environment:
      TZ: Asia/Tokyo
  wordpress:
    restart: always
    environment:
      TZ: Asia/Tokyo
  mysql:
    restart: always
    environment:
      TZ: Asia/Tokyo
  netdata:
    restart: always
    environment:
      TZ: Asia/Tokyo
