version: '3'

services:
  # データベース
  database:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - './conf/my.cnf:/etc/mysql/conf.d/azisaba.cnf'
      - '/srv/mysql:/var/lib/mysql'
  # ウェブ
  web:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 443:443
    environment:
      TZ: Asia/Tokyo
    volumes:
      - './conf/nginx.conf:/etc/nginx/conf.d/azisaba.conf'
      - '/srv/letsencrypt:/etc/letsencrypt'
      - '/srv/html:/var/www/html'
      - '/opt/repo:/opt/repo'
      - '/opt/buildtools:/opt/buildtools'
    depends_on:
      - wordpress
  # ホームページ
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    restart: always
    environment:
      TZ: Asia/Tokyo
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: '${WP_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WP_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WP_DB_NAME}'
    volumes:
      - './conf/php.ini:/usr/local/etc/php/php.ini'
      - './conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf'
      - '/srv/html/azisaba.net:/var/www/html/azisaba.net'
    depends_on:
      - database
