version: '3.1'

services:
  # データベース
  database:
    build:
      context: ./images/mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
    volumes:
      - './conf/my.cnf:/etc/my.cnf.d/azi.cnf'
      - '/srv/mysql:/var/lib/mysql'
  # 証明書
  letsencrypt:
    build:
      context: ./images/letsencrypt
    secrets:
      - dns-cloudflare
    environment:
      TZ: Asia/Tokyo
      DOMAINS: 'azisaba.net,*.azisaba.net'
      DNS_CLOUDFLARE_CREDENTIALS: '/run/secrets/dns-cloudflare'
    volumes:
      - '/srv/letsencrypt:/etc/letsencrypt'
  # ウェブ
  web:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 443:443
    environment:
      TZ: Asia/Tokyo
    volumes:
      - './conf/nginx.conf:/etc/nginx/conf.d/azi.conf'
      - '/srv/letsencrypt:/app/letsencrypt'
      - '/srv/html/azisaba.net:/app/html/azisaba.net'
      - '/srv/html/maps.azisaba.net:/app/html/maps.azisaba.net'
      - '/opt/resourcepacks:/app/resourcepacks'
    depends_on:
      - wordpress
      - metabase
  # ホームページ
  wordpress:
    build:
      context: ./images/wordpress
    restart: always
    secrets:
      - wordpress
    environment:
      TZ: Asia/Tokyo
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD_FILE: '/run/secrets/wordpress'
      WORDPRESS_DB_NAME: 'azisaba_wordpress'
    volumes:
      - './conf/php.ini:/usr/local/etc/php/php.ini'
      - './conf/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-www.conf'
      - '/srv/html/azisaba.net:/app/html/azisaba.net'
    depends_on:
      - database
  # WebP作成
  wordpress-webp:
    build:
      context: ./images/webp
    environment:
      TZ: Asia/Tokyo
    volumes:
      - '/srv/html/azisaba.net/wp-content/uploads:/app/wordpress-webp'
    working_dir: '/app/wordpress-webp'
  # データ可視化
  metabase:
    image: metabase/metabase:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
      MB_DB_FILE: /app/metabase/metabase.db
    volumes:
      - '/srv/metabase:/app/metabase'
  # アジ鯖ロガー
  logger:
    build:
      context: ./images/discord.py
    restart: always
    environment:
      TZ: Asia/Tokyo
      SCRIPT_PATH: 'AzisabaLogger.py'
    volumes:
      - '/srv/discord/logger:/app/logger'
    working_dir: '/app/logger'
  # アジ鯖サポート
  support:
    build:
      context: ./images/discord.py
    restart: always
    environment:
      TZ: Asia/Tokyo
      SCRIPT_PATH: 'support.py'
    volumes:
      - '/srv/discord/support:/app/support'
    working_dir: '/app/support'
  # Minecraft - bungee (バンジーサーバー)
  bungee:
    build:
      context: ./images/minecraft
    restart: always
    ports:
      - 8192:8192
      - 25565:25565
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'end'
      JAR_PATH: 'BungeeCord.jar'
      JVM_ARGS: '-Dminecraft@bungee -Xms3G -Xmx3G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/bungee:/app/bungee'
    working_dir: '/app/bungee'
  # Minecraft - lobby (ロビーサーバー)
  lobby:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'spigot-1.8.8.jar'
      JVM_ARGS: '-Dminecraft@lobby -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/lobby:/app/lobby'
    working_dir: '/app/lobby'
  # Minecraft - main (生活サーバー)
  main:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'paper-1.13.2.jar'
      JVM_ARGS: '-Dminecraft@main -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/main:/app/main'
    working_dir: '/app/main'
  # Minecraft - parkour (パルクールサーバー)
  parkour:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'paper-1.13.2.jar'
      JVM_ARGS: '-Dminecraft@parkour -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/parkour:/app/parkour'
    working_dir: '/app/parkour'
  # Minecraft - p (観光サーバー)
  p:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'paper-1.13.2.jar'
      JVM_ARGS: '-Dminecraft@p -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/p:/app/p'
    working_dir: '/app/p'
  # Minecraft - lgw (銃サーバー)
  lgw:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'paper-1.12.2.jar'
      JVM_ARGS: '-Dminecraft@lgw -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/lgw:/app/lgw'
    working_dir: '/app/lgw'
  # Minecraft - pvp (PvPサーバー)
  pvp:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'spigot-1.8.8.jar'
      JVM_ARGS: '-Dminecraft@pvp -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:CompileCommand=exclude,java.io.PrintStream::write'
    volumes:
      - '/opt/minecraft/pvp:/app/pvp'
    working_dir: '/app/pvp'
  # Minecraft - pata (ぱたサーバー)
  pata:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'spigot-1.8.8.jar'
      JVM_ARGS: '-Dminecraft@pata -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/pata:/app/pata'
    working_dir: '/app/pata'
  # Minecraft - silo-pvp (白猫サーバー)
  silo-pvp:
    build:
      context: ./images/minecraft
    restart: always
    environment:
      TZ: Asia/Tokyo
      STOP_CMD: 'minecraft:stop'
      JAR_PATH: 'spigot-1.8.8.jar'
      JVM_ARGS: '-Dminecraft@silo-pvp -Xms6G -Xmx6G -XX:+AlwaysPreTouch -XX:+UseShenandoahGC -XX:+DisableExplicitGC -XX:-UseBiasedLocking -XX:ActiveProcessorCount=4'
      JAVA_TOOL_OPTIONS: '-Xloggc:./gc.log -XX:+PrintGCDateStamps -XX:+PrintGCDetails'
    volumes:
      - '/opt/minecraft/silo-pvp:/app/silo-pvp'
    working_dir: '/app/silo-pvp'

secrets:
  wordpress:
    file: /srv/secrets/wordpress.txt
  dns-cloudflare:
    file: /srv/secrets/dns-cloudflare.txt
