version: '3.7'

services:
  database:
    image: mariadb:10.5.4-focal
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data/minecraft-mariadb:/var/lib/mysql
    command: --gdb --max-connections=1000
  mcredis:
    image: redis:6.0.6-alpine
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./data/minecraft-redis:/data
  bungee:
    image: ghcr.io/azisaba/bungee
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8192:8192
      - 25565:25577
  lobby:
    image: ghcr.io/azisaba/lobby
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./worlds/lobby_world:/app/world
      - ./worlds/lobby_lobby:/app/lobby
  rzh: { image: adoptopenjdk:8-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/rzh:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@rzh -jar paper-1.12.2.jar }
  pvp: { image: adoptopenjdk:8-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/pvp:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@pvp -jar paper-1.8.8.jar }
  parkour: { image: adoptopenjdk:13-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/parkour:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@parkour -jar paper-1.13.2.jar }
  life:
    image: yukileafx/minecraft-alpine:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /opt/minecraft/life:/app
    command: 'java -Dazi@life -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.15.2.jar'
    depends_on:
      - database
  lgw:
    image: yukileafx/minecraft-alpine:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /opt/minecraft/lgw:/app
    command: 'java -Dazi@lgw -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.12.2.jar'
    depends_on:
      - database
  lgwf: { image: adoptopenjdk:13-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/lgwf:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@lgwf -jar paper-1.14.4.jar }
  chibi: { image: adoptopenjdk:14-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/chibi:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@chibi -jar paper-1.15.2.jar }
  rpg: { image: adoptopenjdk:14-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/rpg:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@rpg -jar paper-1.15.2.jar }
  afk: { image: adoptopenjdk:8-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/afk:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@afk -jar paper-1.8.8.jar }
  fsw: { image: adoptopenjdk:14-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/fsw:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@fsw -jar paper-1.12.2.jar }
  coretol: { image: adoptopenjdk:14-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/coretol:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@coretol -jar paper-1.15.2.jar }
  event: { image: adoptopenjdk:13-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/event:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@event -jar paper-1.13.2.jar }
  mksrv: { image: adoptopenjdk:14-jre-hotspot, restart: always, environment: { TZ: Asia/Tokyo }, volumes: [ /opt/minecraft/mksrv:/app ], working_dir: /app, tty: true, stop_signal: SIGINT, command: java -Dlegacy@mksrv -jar paper-1.16.2.jar }
