version: "3.7"

x-legacyapp: &legacyapp
  restart: always
  working_dir: /app
  tty: true
  environment:
    TZ: Asia/Tokyo
  stop_grace_period: 1m
  stop_signal: SIGINT

services:
  letsencrypt:
    image: certbot/dns-cloudflare
    volumes:
      - ./load/cloudflare.ini:/cf
      - ./save/letsencrypt:/etc/letsencrypt
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cf -m ledlaggazi@gmail.com --agree-tos -n -d azisaba.net -d *.azisaba.net --keep
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /srv:/srv
      - ./save/filebrowser.db:/database.db
      - ./save/filebrowser.json:/.filebrowser.json
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./load/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./save/letsencrypt:/ssl
    depends_on:
      - filebrowser
    networks:
     - nginx_network
     - default
  life:
    <<: *legacyapp
    image: openjdk:14
    ports:
      - 49999:25565
    volumes:
      - /srv/life:/app
    command: java -jar paper-1.15.2.jar
  lifebuild:
    <<: *legacyapp
    image: openjdk:14
    ports:
      - 50011:25565
    volumes:
      - /srv/lifebuild:/app
    command: java -jar paper-1.15.2.jar
  coretol:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50009:25565
    volumes:
      - /srv/coretol:/app
    working_dir: /app/lobby
    command: java -jar paper-1.15.2.jar
  coretol_season1_build:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50020:25565
    volumes:
      - /srv/coretol:/app
    working_dir: /app/season1_build
    command: java -jar paper-1.15.2.jar
  coretol_season1_sv1:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50021:25565
    volumes:
      - /srv/coretol:/app
    working_dir: /app/season1_sv1
    command: java -jar paper-1.15.2.jar
#  coretol_season1_sv2:
#    <<: *legacyapp
#    image: openjdk:11
#    ports:
#      - 50022:25565
#    volumes:
#      - /srv/coretol:/app
#    working_dir: /app/season1_sv2
#    command: java -jar paper-1.15.2.jar
#  coretol_season1_sv3:
#    <<: *legacyapp
#    image: openjdk:11
#    ports:
#      - 50023:25565
#    volumes:
#      - /srv/coretol:/app
#    working_dir: /app/season1_sv3
#    command: java -jar paper-1.15.2.jar
#  coretol_season1_sv4:
#    <<: *legacyapp
#    image: openjdk:11
#    ports:
#      - 50024:25565
#    volumes:
#      - /srv/coretol:/app
#    working_dir: /app/season1_sv4
#    command: java -jar paper-1.15.2.jar
#  coretol_season1_sv5:
#    <<: *legacyapp
#    image: openjdk:11
#    ports:
#      - 50025:25565
#    volumes:
#      - /srv/coretol:/app
#    working_dir: /app/season1_sv5
#    command: java -jar paper-1.15.2.jar
#  coretol_season1_sv6:
#    <<: *legacyapp
#    image: openjdk:11
#    ports:
#      - 50026:25565
#    volumes:
#      - /srv/coretol:/app
#    working_dir: /app/season1_sv6
#    command: java -jar paper-1.15.2.jar
  event:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50002:25565
    volumes:
      - /srv/event:/app
    command: java -jar paper-1.13.2.jar
  asterpvp:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50004:25565
    volumes:
      - /srv/asterpvp:/app
    command: java -jar paper-1.12.2.jar
  conquest:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50013:25565
    volumes:
      - /srv/conquest:/app
    command: java -jar paper-1.14.4.jar 
  rzh:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50003:25565
    volumes:
      - /srv/rzh:/app
    command: java -jar paper-1.12.2.jar
  rms:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50014:25565
    volumes:
      - /srv/rms:/app
    command: java -jar paper-1.16.5.jar
  tsl:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50010:25565
    volumes:
      - /srv/tsl:/app
    command: java -jar paper-1.16.5.jar 
  jg24:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50015:25565
    volumes:
      - /srv/jg24:/app
    command: java -jar paper-1.16.5.jar
  mkna:
    <<: *legacyapp
    image: openjdk:16
    ports:
      - 50016:25565
    volumes:
      - /srv/mkna:/app
    command: java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper-1.16.5.jar nogui

networks:
  nginx_network:
    external: true
