version: "3.7"

x-legacyapp: &legacyapp
  restart: always
  working_dir: /app
  tty: true
  environment:
    TZ: Asia/Tokyo
  stop_grace_period: 1m
  stop_signal: SIGINT

services:
  letsencrypt:
    image: certbot/dns-cloudflare
    volumes:
      - ./load/cloudflare.ini:/cf
      - ./save/letsencrypt:/etc/letsencrypt
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cf -m ledlaggazi@gmail.com --agree-tos -n -d azisaba.net -d *.azisaba.net --keep
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /srv:/srv
      - ./save/filebrowser.db:/database.db
      - ./save/filebrowser.json:/.filebrowser.json
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./load/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./save/letsencrypt:/ssl
    depends_on:
      - filebrowser
    networks:
     - nginx_network
     - default
  life:
    <<: *legacyapp
    image: openjdk:14
    ports:
      - 49999:25565
    volumes:
      - /srv/life:/app
    command: java -jar paper-1.15.2.jar
  lifebuild:
    <<: *legacyapp
    image: openjdk:14
    ports:
      - 50011:25565
    volumes:
      - /srv/lifebuild:/app
    command: java -jar paper-1.15.2.jar
  coretol:
    <<: *legacyapp
    image: openjdk:11
    ports:
      - 50009:25565
    volumes:
      - /srv/coretol:/app
    working_dir: /app/season1
    command: java -jar paper-1.15.2.jar
  event:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50002:25565
    volumes:
      - /srv/event:/app
    command: java -jar paper-1.13.2.jar
  asterpvp:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50004:25565
    volumes:
      - /srv/asterpvp:/app
    command: java -jar paper-1.12.2.jar
  conquest:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50013:25565
    volumes:
      - /srv/conquest:/app
    command: java -jar paper-1.14.4.jar 
  rzh:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50003:25565
    volumes:
      - /srv/rzh:/app
    command: java -jar paper-1.12.2.jar
  rms:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50014:25565
    volumes:
      - /srv/rms:/app
    command: java -jar paper-1.16.5.jar
  mksrv:
    <<: *legacyapp
    image: openjdk:8
    ports:
      - 50010:25565
    volumes:
      - /srv/mksrv:/app
    command: java -jar paper-1.16.5.jar 

networks:
  nginx_network:
    external: true
