version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:latest
    working_directory: ~/work
    environment:
      TZ: Asia/Tokyo

jobs:
  build:
    executor: alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add docker
      - run: apk add docker-compose
      - run: docker-compose pull
      - run: docker-compose build --parallel
      - run: docker system df -v

workflows:
  version: 2
  commit: { jobs: [build] }
