version: '3.7'

services:
  database:
    restart: always
    environment:
      TZ: Asia/Tokyo
  bungee:
    restart: always
    environment:
      TZ: Asia/Tokyo
  lobby:
    restart: always
    environment:
      TZ: Asia/Tokyo
  main:
    restart: always
    environment:
      TZ: Asia/Tokyo
  wave:
    restart: always
    environment:
      TZ: Asia/Tokyo
  pvp:
    restart: always
    environment:
      TZ: Asia/Tokyo
  parkour:
    restart: always
    environment:
      TZ: Asia/Tokyo
  life:
    restart: always
    environment:
      TZ: Asia/Tokyo
  lgw:
    restart: always
    environment:
      TZ: Asia/Tokyo
  chibi:
    restart: always
    environment:
      TZ: Asia/Tokyo
  rpg:
    restart: always
    environment:
      TZ: Asia/Tokyo
