version: '3.7'

services:
  database:
    image: mariadb:10.5.4-focal
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ../../data/minecraft-mariadb:/var/lib/mysql
    command: --gdb --max-connections=1000
  mcredis:
    image: redis:6.0.6-alpine
    volumes:
      - ../../data/minecraft-redis:/data
  bungee:
    image: yukileafx/azi-waterfall
    ports:
      - 8192:8192
      - 25565:25577
  lobby:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/lobby:/app
    command: 'java -Dazi@lobby -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.8.8.jar'
    depends_on:
      - database
  wave:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/wave:/app
    command: 'java -Dazi@wave -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -Dbungee=true -jar Yukkit.jar'
    depends_on:
      - database
  pvp:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/pvp:/app
    command: 'java -Dazi@pvp -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.8.8.jar'
    depends_on:
      - database
  parkour:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/parkour:/app
    command: 'java -Dazi@parkour -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.13.2.jar'
    depends_on:
      - database
  life:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/life:/app
    command: 'java -Dazi@life -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.15.2.jar'
    depends_on:
      - database
  lgw:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/lgw:/app
    command: 'java -Dazi@lgw -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -Dbungee=true -jar Yukkit.jar'
    depends_on:
      - database
  lgwf:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/lgwf:/app
    command: 'java -Dazi@lgwf -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -Dbungee=true -jar Yukkit.jar'
    depends_on:
      - database
  chibi:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/chibi:/app
    command: 'java -Dazi@chibi -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.15.2.jar'
    depends_on:
      - database
  rpg:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/rpg:/app
    command: 'java -Dazi@rpg -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.15.2.jar'
    depends_on:
      - database
  afk:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/afk:/app
    command: 'java -Dazi@afk -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.8.8.jar'
    depends_on:
      - database
  fsw:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/fsw:/app
    command: 'java -Dazi@fsw -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.12.2.jar'
    depends_on:
      - database
  coretol:
    image: yukileafx/minecraft-alpine:latest
    volumes:
      - /opt/minecraft/coretol:/app
    command: 'java -Dazi@coretol -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -jar paper-1.15.2.jar'
    depends_on:
      - database
