name: Docker

on: [push]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)"
          chmod -c +x hadolint
      - run: hadolint --version
      - run: find . -type f -name "Dockerfile" -print0 | xargs -0 hadolint --ignore DL3018
