name: Docker

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget -O hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)"
      - run: chmod -c +x hadolint
      - run: sudo cp -v hadolint /usr/local/bin/hadolint
      - run: hadolint --version
      - run: find . -type f -name Dockerfile -print0 | xargs -0t hadolint

  #pull:
  #  name: Pull
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: docker version
  #    - run: docker-compose version
  #    - run: docker-compose --no-ansi pull
  #    - run: docker image ls --filter dangling=false

  #build:
  #  name: Build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: docker version
  #    - run: docker-compose version
  #    - run: docker-compose --no-ansi build
