name: Docker

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd /usr/local/bin
          sudo curl -L -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)"
          sudo chmod -c +x hadolint
      - run: hadolint --version
      - run: find . -type f -name "Dockerfile" -print0 | xargs -0 hadolint --ignore DL3018
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker version
      - run: docker-compose version
      - run: |
          docker-compose pull
          docker-compose build
      - run: docker system df
      - run: docker system df --verbose
