name: Docker

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://hadolint/hadolint
        with:
          args: /bin/ash -c 'hadolint --version && find . -type f -name Dockerfile -print0 | xargs -0t hadolint'
