---
name: Docker
"on": [push]

jobs:
  build:
    name: ${{ matrix.compose }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose: [pull, build]
    steps:
      - uses: actions/checkout@v2
      - run: docker version
      - run: docker-compose version
      - run: docker-compose --no-ansi ${{ matrix.compose }}
