name: Docker

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://hadolint/hadolint
        with:
          entrypoint: /bin/ash -c
          args: hadolint --version
