---
name: Shell
"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
      - run: tar -xJv -f shellcheck-stable.linux.x86_64.tar.xz
      - run: sudo cp -v shellcheck-stable/shellcheck /usr/local/bin/shellcheck
      - run: shellcheck --version
      - run: find . -type f -name "*.sh" -print0 | xargs -0t shellcheck -e SC2187
