name: Shell

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install shellcheck
      - run: shellcheck --version
      - run: find . -type f -name '*.sh' -print0 | xargs -0t shellcheck
