name: Shell

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://koalaman/shellcheck
        with:
          args: /bin/bash -c "shellcheck --version && find . -type f -name '*.sh' -print0 | xargs -0t shellcheck"
