name: Shell

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://koalaman/shellcheck
        with:
          args: --version
      - uses: docker://koalaman/shellcheck
        with:
          entrypoint: /bin/bash
          args: -c "find . -type f -name '*.sh' -print0 | xargs -0t shellcheck"
