name: Docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose:
          - apps/web/base.yml:apps/web/compose.yml
          - apps/minecraft/base.yml:apps/minecraft/compose.yml
    env:
      COMPOSE_FILE: ${{ matrix.compose }}
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose --no-ansi pull
      - run: docker-compose --no-ansi build
      - run: docker-compose --no-ansi up -d
      - run: docker-compose --no-ansi stop
      - run: docker-compose --no-ansi logs
      - run: docker-compose --no-ansi rm -f
      - run: sudo find . \( -not -path './.git/*' \)
