---

name: Yaml

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - run: python --version
      - run: pip install yamllint
      - run: yamllint --version
      - run: yamllint .
